config/routes.rb
RedditClone::Application.routes.draw do
	resources :comments, :only => [:create, :show]
	resources :links do
		post 'downvote'
		post 'upvote'
	end
  resource :session, :only => [:new, :create, :destroy]
  resources :subs
  resources :users, :only => [:new, :create, :show]
  
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  link_id    :integer
#  parent_id  :integer
#  body       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  author_id  :integer
#

class Comment < ActiveRecord::Base
  attr_accessible :body, :parent_id, :link_id, :parent, :children

  validates :body, :presence => true
  validates :link_id, :presence => true

  belongs_to :link
  belongs_to :author, :class_name => "User"

  def children
  	self.class.where( :parent_id => self.id )
  end

end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  url        :string(255)
#  body       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  author_id  :integer
#

class Link < ActiveRecord::Base
  attr_accessible :body, :title, :url, :author_id, :sub_ids

  before_create :set_default_score

  validates :title, :body, :presence => true

  belongs_to :author, :class_name => "User"

  has_many :link_subs
  has_many :subs, :through => :link_subs
  has_many :comments, :inverse_of => :link

  has_many :user_votes

  def set_default_score
  	self.score ||= 0
  end
end

app/models/link_sub.rb
# == Schema Information
#
# Table name: link_subs
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  sub_id     :integer
#  link_id    :integer
#

class LinkSub < ActiveRecord::Base
  attr_accessible :link_id, :sub_id

  belongs_to :link
  belongs_to :sub
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  moderator_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  attr_accessible :name, :links, :links_attributes

  validates :name, :presence => true
  								 # :uniqueness => true

  validates :moderator_id, :presence => true

  belongs_to :moderator, :class_name => "User"

  has_many :link_subs, :inverse_of => :sub

  has_many :links, :through => :link_subs
  accepts_nested_attributes_for :links, :reject_if => lambda { |attributes| attributes['url'].blank? }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)
#  password_digest :string(255)
#  session_token   :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :password, :session_token, :username

  validates :username, :presence => true,
  										 :uniqueness => true

  validates :password_digest, :presence => true

  has_many :moderated_subs, :class_name => "Sub", :foreign_key => :moderator_id
  has_many :authored_links, :class_name => "Link", :foreign_key => :author_id
  has_many :authored_comments, :class_name => "Comment", :foreign_key => :author_id

  has_many :user_votes
  has_many :links_voted_on, :through => :user_votes, :source => :link

  def password=(password)
  	self.password_digest = BCrypt::Password.create(password)
  end

  def correct_password?(password_attempt)
  	BCrypt::Password.new(self.password_digest) == password_attempt
  end

  def generate_session_token!
  	self.session_token = SecureRandom.urlsafe_base64(16)
  	self.save!
  end

  def destroy_session_token!
  	self.session_token = nil
  	self.save!
  end
end

app/models/user_vote.rb
class UserVote < ActiveRecord::Base
  attr_accessible :link_id, :user_id

  belongs_to :link
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :logged_in?

  include LinksHelper

  def require_login
  	unless logged_in?
  		redirect_to new_session_url
  	end
  end

  def login(user)
  	user.generate_session_token!
  	session[:session_token] = user.session_token
  end

  def logout(user)
  	user.destroy_session_token!
  	session[:session_token] = nil
  end

  def current_user
  	return nil unless session[:session_token]
  	@current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
  	!!current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@comment = current_user.authored_comments.build(params[:comment])
		@link = @comment.link
		if @comment.save
			redirect_to comment_url(@comment)
		else
			redirect_to link_url(@comment.link)
		end
	end

	def show
		@comment = Comment.find(params[:id])
		@link = @comment.link
	end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

	def create
		# @link = Link.new(params[:link])
		# @link.author_id = current_user.id
		@link = current_user.authored_links.build(params[:link])
		if @link.save
			redirect_to link_url(@link)
		else
			render :new
		end
	end

	def new
		@link = Link.new
	end

	def update
		@link = Link.find(params[:id])
		if @link.update_attributes(params[:link])
			redirect_to link_url(@link)
		else
			render :edit
		end
	end

	def edit
		@link = Link.find(params[:id])
	end

	def show
		@already_rendered = []
		@link = Link.find(params[:id])
		@comments = @link.comments
	end

	def destroy
	end

	def upvote
		u = current_user
		link = Link.find(params[:link_id])
		if u.links_voted_on.include?(link)
			flash[:errors] ||= []
			flash[:errors] << "Can't vote on the same link twice!"
			redirect_to link_url(link)
			return
		end
		vote = u.user_votes.build(:link_id => params[:link_id])
		u.save!
		link.score += 1
		link.save!
		redirect_to link_url(link)
	end

	def downvote
		u = current_user
		link = Link.find(params[:link_id])
		if u.links_voted_on.include?(link)
			flash[:errors] ||= []
			flash[:errors] << "Can't vote on the same link twice!"
			redirect_to link_url(link)
			return
		end
		vote = u.user_votes.build(:link_id => params[:link_id])
		u.save!
		link.score -= 1
		link.save!
		redirect_to link_url(link)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		@user = User.find_by_username(params[:user][:username])
		if @user && @user.correct_password?(params[:user][:password])
			login(@user)
			redirect_to user_url(@user)
		else
			@user = User.new(params[:user])
			render :new
		end
	end

	def new
		u = current_user
		redirect_to user_url(u) if u 
		@user = User.new
	end

	def destroy
		u = current_user
		logout(u)
		redirect_to new_session_url
	end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

	def index
		@subs = Sub.all
	end

	def create
		@sub = current_user.moderated_subs.build(params[:sub])
		if @sub.save
			redirect_to sub_url(@sub)
		else
			render :new
		end
	end

	def new
		@sub = Sub.new
	end

	def show
		@sub = Sub.find(params[:id])
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def create
		@user = User.new(params[:user])
		if @user.save
			login(@user)
			redirect_to user_url(@user)
		else
			render :new
		end
	end

	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
		@moderated_subs = @user.moderated_subs
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/show.html.erb
<h2>Viewing Comment</h2>

<p><%= @comment.body %></p>

<p>Posted by <%= @comment.author.username %> - <em><%= time_ago_in_words(@comment.created_at)  + " ago" %></em>

<h4>Comment on this Comment</h4>
<form action="<%= comments_url %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<input type="hidden" name="comment[link_id]" value="<%= @link.id %>">
	<input type="hidden" name="comment[parent_id]" value="<%= @comment.id %>">

	<label for="comment_body">Comment Body</label>
	<br />
	<textarea id="comment_body" name="comment[body]"></textarea>

	<br />

	<input type="submit" value="Create Comment">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
	<%= button_to "Sign Out", session_url, :method => :delete %>
	<p>Current User: <%= current_user.username %></p>
	<p>Session Token: <%= session[:session_token] %></p>
<% else %>
	<%= link_to "Sign In", new_session_url %>
<% end %>
<hr>
<%= yield %>

</body>
</html>

app/views/links/_comment.html.erb
<li>
	<%= comment.body %>
	<% if comment.children.present? %>
		<ul>
			<%= render :partial => 'comment', :collection => comment.children, :locals => { :already_rendered => already_rendered } %>
		</ul>
	<% end %>
</li>

app/views/links/_form.html.erb
<% if intent == "new" %>
	<% text, action_url = "Create Link", links_url %>
<% elsif intent == "edit" %>
	<% text, action_url = "Edit Link", link_url(link) %>
<% end %>

<h2><%= text %></h2>

<form action="<%= action_url %>" method="post">
	<% if intent == "edit" %>
		<input type="hidden" name="_method" value="put">
	<% end %>

	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

	<label for="link_title">Title</label>
	<input type="text" id="link_title" name="link[title]" value="<%= link.title %>">

	<br />

	<label for="link_url">URL</label>
	<input type="text" id="link_url" name="link[url]" value="<%= link.url %>">

	<br />

	<label for="link_body">Body</label>
	<br />
	<textarea id="link_body" name="link[body]"><%= link.body %></textarea>

	<br />

	<p>Associated Subs</p>
	<% Sub.all.each do |sub| %>
		<input
			type="checkbox"
			name="link[sub_ids][]"
			value="<%= sub.id %>"
			id="link_sub_ids_<%= sub.id %>"
			<%= "checked" if sub.links.include?(link) %>>
		<label for="link_sub_ids_<%= sub.id %>"><%= sub.name %></label>
		<br />
	<% end %>

	<input type="hidden" name="link[sub_ids][]" value="">
	<input type="submit" value="<%= text %>">
</form>

app/views/links/edit.html.erb
<%= render :partial => 'form', :locals => {
	:link => @link,
	:intent => "edit"
	} %>

app/views/links/new.html.erb
<%= render :partial => 'form', :locals => {
	:link => @link,
	:intent => "new"
	} %>

app/views/links/show.html.erb
<h2><%= @link.title %></h2>

<p><em><%= @link.url %></em></p>

<p><%= @link.body %></p>

<h4>Comments</h4>
<ul>
	<% @comments.where( :parent_id => nil ).each do |comment| %>
		<%= render :partial => 'comment', :object => comment, :locals => {
			:already_rendered => @already_rendered
		} %>
	<% end %>
</ul>

<h4>Add Comment</h4>
<form action="<%= comments_url %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<input type="hidden" name="comment[link_id]" value="<%= @link.id %>"

	<label for="comment_body">Comment Body</label>
	<br />
	<textarea id="comment_body" name="comment[body]"></textarea>

	<br />

	<input type="submit" value="Create Comment">
</form>

app/views/shared/_signin_form.html.erb
<% if intent == "signup" %>
	<% action_url = users_url %>
	<% text = "Sign Up" %>
<% elsif intent == "signin" %>
	<% action_url = session_url %>
	<% text = "Sign In" %>
<% end %>

<h2><%= text %></h2>

<form action="<%= action_url %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

	<label for="username">Username</label>
	<input type="text" name="user[username]" id="username" value="<%= user.username %>">

	<br />

	<label for="password">Password</label>
	<input type="password" name="user[password]" id="password">

	<br />

	<input type="submit" value="<%= text %>">
</form>

app/views/subs/index.html.erb
<h2>All the Subs</h2>

<ul>
	<% @subs.each do |sub| %>
		<li><%= link_to sub.name, sub_url(sub) %></li>
		<% sub.links.sort_by { |link| link.score }.reverse.try(:each) do |link| %>
		<ul>
			<li>
				<strong><%= link.title %></strong> - <em><%= link_to link.url, link_url(link) %> (<%= link.score %>)</em>
				<br />
				<% if link.author_id == current_user.id %>
					<%= button_to "Edit Link", edit_link_url(link), :method => :get %>
				<% end %>
				<% unless current_user.links_voted_on.include?(link) %>
					<%= button_to "Upvote", link_upvote_url(link) %>
					<%= button_to "Downvote", link_downvote_url(link) %>
				<% end %>
			</li>
		</ul>
		<% end %>
	<% end %>
</ul>

app/views/subs/new.html.erb
<h2>Create New Sub</h2>

<form action="<%= subs_url %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

	<p>
		<label for="sub_name">Sub Name</label>
		<input type="text" id="sub_name" name="sub[name]" value="<%= @sub.name %>">
	</p>

	<p>Links</p>
	<% 5.times do |i| %>
		<% title_id = "sub_links_attributes_#{i}_title" %>
		<% url_id = "sub_links_attributes_#{i}_url" %>
		<% body_id = "sub_links_attributes_#{i}_body" %>
		<p>Link <%= i+1 %></p>
		
		<input type="hidden" name="sub[links_attributes][<%= i %>][author_id]" value="<%= current_user.id %>">

		<label for="<%= title_id %>">Title</label>
		<input type="text" id="<%= title_id %>" name="sub[links_attributes][<%= i %>][title]">

		<br />

		<label for="<%= url_id %>">URL</label>
		<input type="text" id="<%= url_id %>" name="sub[links_attributes][<%= i %>][url]">

		<br />

		<label for="<%= body_id %>">Body</label>
		<br />
		<textarea id="<%= body_id %>" name="sub[links_attributes][<%= i %>][body]"></textarea>

		<br />

	<% end %>

	<input type="submit" value="Create Sub">

</form>

app/views/subs/show.html.erb
<h2><%= @sub.name %></h2>

<ul>
	<% @sub.links.sort_by { |link| link.score }.reverse.try(:each) do |link| %>
		<li>
			<strong><%= link.title %></strong> - <em><%= link_to link.url, link_url(link) %> (<%= link.score %>)</em>
			<br />
			<% if link.author_id == current_user.id %>
				<%= button_to "Edit Link", edit_link_url(link), :method => :get %>
			<% end %>
			<% unless current_user.links_voted_on.include?(link) %>
				<%= button_to "Upvote", link_upvote_url(link) %>
				<%= button_to "Downvote", link_downvote_url(link) %>
			<% end %>
		</li>
	<% end %>
</ul>

app/views/users/new.html.erb
<%= render :partial => 'shared/signin_form', :locals => {
	:user => @user,
	:intent => "signup"
	} %>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>

<h4>Moderated Subs:</h4>
<ul>
	<% @moderated_subs.each do |sub| %>
		<li><%= link_to sub.name, sub_url(sub) %></li>
	<% end %>
</ul>